apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-installer-config
  namespace: node-installer
data:
  install.sh: |
    #!/bin/bash

    # Update and install packages
    sudo apt-get update
    sudo apt-get install cowsay -y

    touch /vagrant/samplefile.txt

  cleanup.sh: |
    #!/bin/bash

    sudo apt-get remove cowsay -y
    rm /vagrant/samplefile.txt
