apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-installer-config
  namespace: node-installer
data:
  install.sh: |
    #!/bin/bash

    # Update and install packages
    apt-get update
    apt-get install cowsay -y

    touch /vagrant/samplefile.txt

  cleanup.sh: |
    #!/bin/bash

    apt-get remove cosway
    rm /vagrant/samplefile.txt
